# Write your MySQL query statement below
SELECT ROUND(SUM(TIV_2016), 2) AS TIV_2016 
FROM INSURANCE
WHERE (LAT, LON) IN (
    SELECT LAT, LON
    FROM INSURANCE
    GROUP BY LAT, LON
    HAVING COUNT(*) = 1
)
AND tiv_2015 IN (
    SELECT tiv_2015
    FROM Insurance
    GROUP BY tiv_2015
    HAVING COUNT(*) > 1
);