# Write your MySQL query statement below
#DENSE_RANK = USE TO SORT ON THE BASIS ON RANKING OVER (ORDER BY SCORE DESC) AS "RANK" FROM SCORES; THIS IS THE WINDO FUNCTION

SELECT SCORE, DENSE_RANK() OVER (ORDER BY SCORE DESC) AS "RANK" FROM SCORES;