CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      # Write your MySQL query statement below.
      SELECT SALARY FROM ( SELECT SALARY, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RANKING FROM EMPLOYEE) AS RANKED_SALARIES WHERE RANKING = N LIMIT  1

  );
END